version: 0.2
phases:
  pre_build:
    commands:
      - echo start
  build:
    commands:
      - echo Build started on `date`
      - docker-compose build
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Images pushed to repositories