version: 0.2
env:
  variables:
    APP_IMAGE_REPO_NAME: "my_app"
phases:
  pre_build:
    commands:
      - echo start
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - APP_REPOSITORY_URI=`aws ssm get-parameters --names "/$DEPLOY_STAGE/ECR/app-uri" --with-decryption --region $AWS_DEFAULT_REGION --output text --query Parameters[0].Value`
      - echo deploy_stage $DEPLOY_STAGE
      - echo APP_REPOSITORY_URI $APP_REPOSITORY_URI
      - echo WEB_REPOSITORY_URI $WEB_REPOSITORY_URI
      - docker pull $APP_REPOSITORY_URI:$DEPLOY_STAGE || true
      - docker pull $WEB_REPOSITORY_URI:$DEPLOY_STAGE || true
  build:
    commands:
      - echo Build started on `date`
      - docker-compose build
      - echo Build completed on `date`
  post_build:
    commands:
      - docker tag $APP_IMAGE_REPO_NAME:latest $APP_REPOSITORY_URI:$DEPLOY_STAGE
      - docker tag $WEB_IMAGE_REPO_NAME:latest $WEB_REPOSITORY_URI:$DEPLOY_STAGE
      - echo Images tagged
      - docker push $APP_REPOSITORY_URI:$DEPLOY_STAGE
      - docker push $WEB_REPOSITORY_URI:$DEPLOY_STAGE
      - echo Images pushed to repositories