version: '3'

services:
  db:
    restart: always
    image: postgres:9.6-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  web:
    restart: always
    env_file: .env
    build: .
    container_name: 'reviews_web'
    command: ./entrypoint.sh
    volumes:
      - .:/src
      - /static:/src/static
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  nginx:
    restart: always
    container_name: nginx_server
    build:
      context: ./docker_compose/
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  postgres_data:
  redis_data:
